config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'
  get 'welcome/home'
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        omniauth_callbacks: 'users/omniauth_callbacks'
        
      }
   resources :profiles
  resources :posts do 
    member do 
      get :like
    end
    collection do
      get :search
    end
    resources :comments, only: [:index, :new, :create]
  end
  #resources :comments, only: [:edit, :show, :update, :destroy]
  resources :comments, except: [:index, :new, :create] do 
    member do 
      get :like
    end
  end
  #root 'posts#index'
  
end

app/models/profile.rb
class Profile < ApplicationRecord
	belongs_to :user
  mount_uploader :image, ImageUploader

  
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	before_action :set_profile, only: [:edit, :update]
	def new
		@profile = Profile.new
	end
	
	def create
		@profile = current_user.build_profile(profile_params)
		if @profile.save
			
    		redirect_to posts_path
  		else
    		render 'new'
  		end
	end
	
	def edit
		@profile = Profile.find(params[:id])
	end
	
	def update
		
		@profile.update(profile_params)    	
		render json: { success: true, message: "Profile updated successfully!" }
	end
	
	def show
		@profile = Profile.find(params[:id])
	end

	private
	def set_profile
  		@profile = current_user.profile
	end
	def profile_params
		params.require(:profile).permit(:fname, :lname, :address, :image)
	end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_for @profile, id:"form1", runat:"server" do |f| %>
  <p>
    <%= f.label :"first name" %><br>
    <%= f.text_field :fname %>
  </p>
 
  <p>
    <%= f.label :"Last Name" %><br>
    <%= f.text_field :lname %>
  </p>
  <p>
    <%= f.label :"Address" %><br>
    <%= f.text_field :address %>
  </p>
  <p>
    <%= f.label :"Image" %><br>
    <%= f.file_field :image, id: "userimage" %>
  </p>
  <img id="preview" src="#" alt="your image" />

   <p>
    <%= f.submit :save %>
  </p>
 <%= link_to 'Ajax Submit', '#-', id: "ajaxsubmit" %>  
<% end %>
<!-- <button id= "ajaxsubmit" > ajax </button> -->

app/views/profiles/_show.html.erb
<div class="container">
	<div class="profile-img" align="center">
  		<%= image_tag (@profile.image_url.to_s) %>
	</div>
	<strong>First name:</strong>
  	<span><div class="post">
  		<%= @profile.fname %>
	</div></span>
  	<strong>Last name:</strong>
  	<div class="post">
 		<%= @profile.lname %>
	</div>
  	<strong>Address:</strong>
	<div class="post">
  		<%= @profile.address %>
	</div>
</div>

app/views/profiles/edit.html.erb
<div id="prompt"></div>
<h1>Edit profile</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', profiles_path %>

<script>
$(function(){
    $("#ajaxsubmit").on("click", function(event){
    event.preventDefault();
     var form = this.parentElement
      data = new FormData( form );
      url = $(form).attr('action');
      $.ajax( {
        url: url,
        type: 'PUT',
        data: data,
        processData: false,
        contentType: false,
        success: function(response){
          alert(response.message)
        }
      });
    });
  });
</script>

<script>
function readURL(input) {
   if (input.files && input.files[0]) {
        var reader = new FileReader();
        reader.onload = function (e) {
          $('#preview').attr('src', e.target.result);
        }
        reader.readAsDataURL(input.files[0]);
    }
}
  $("#userimage").change(function(){
    readURL(this);
  });
</script>

app/views/profiles/edit.js.erb
$("#showprofile").html("<%= escape_javascript render(partial: '_show', locals: { profile: @profile }) %>")
$("#prompt").html("success");

app/views/profiles/new.html.erb
<%= render 'profiles/form' %>
 
<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<div class="container">
<div id="showprofile">
	<%= render partial: 'show' %>
</div>
 <%= link_to 'Edit', edit_profile_path(@profile) %>
 <br>
 <%= link_to 'Back', posts_path %> 
</div>

app/views/profiles/update.js.erb
$("#prompt").html("success");