config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'
  get 'welcome/home'
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        omniauth_callbacks: 'users/omniauth_callbacks'
        
      }
   resources :profiles
  resources :posts do 
    member do 
      get :like
    end
    collection do
      get :search
    end
    resources :comments, only: [:index, :new, :create]
  end
  #resources :comments, only: [:edit, :show, :update, :destroy]
  resources :comments, except: [:index, :new, :create] do 
    member do 
      get :like
    end
  end
  #root 'posts#index'
  
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post 
  belongs_to :user
  has_many :likes, :as => :likeable , dependent: :destroy
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	
  def index
    @post = Post.find(params[:post_id])
    @comments = @post.comments
  end
  
  def new
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new
  end
  
  def create
    @post = Post.find(params[:post_id])
    if @post.present?
      @comment = @post.comments.create(comment_params)
      @comment.user_id = current_user.id
      @comment.save
    end
  end

  def edit
   @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    @comment.update(comment_params)
  end

  def destroy
    @comment = Comment.find(params[:id])
    @post = @comment.post
    #@post = Post.find_by(id: @comment.post_id)
    @comment.destroy
  end 

  def like
    @comment = Comment.find(params[:id])
    if @comment.likes.find_by_user_id(current_user.id).present?
      @comment.likes.find_by_user_id(current_user.id)&.destroy
    else
       @comment.likes.create(user_id: current_user.id)
    end
     # redirect_to post_comments_path(id: @comment.id,post_id: @comment.post_id)
  end

  private

  def comment_params
    params.require(:comment).permit(:post_id, :content)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="comment" id="comment-<%= comment.id %>" >
  <%= render partial: "comment_content" , locals: { comment: comment } %>
</div>

app/views/comments/_comment_content.html.erb
<%= comment.content %>
<div class="actions float-right">
  <%= link_to 'Edit', edit_comment_path(comment), remote: true, 'data-toggle': "modal", 'data-target': "#modal-comment"%> |
  <%= link_to 'Destroy', comment_path(comment), method: :delete, remote: true, data: { confirm: 'Are you sure?' } %> |
  <span id="like-comment-<%= comment.id %>">
    <%= render partial: "comment_like", locals: {comment: comment} %>
  </span>
</div>

app/views/comments/_comment_like.html.erb
<% liked = comment.likes.find_by_user_id(current_user.id).present? %>
<% if liked %>
  <%= link_to 'unlike', like_comment_path(id: comment.id), remote: true %>
<% else %>
  <%= link_to 'like', like_comment_path(id: comment.id), remote: true %>
<% end %>
(<%= comment.likes.count %>)

app/views/comments/_edit.html.erb
<!-- Modal Header -->
<div class="modal-header">
	<h4 class="modal-title">Edit comment</h4>
	<button type="button" class="close" data-dismiss="modal">&times;</button>
</div>

<!-- Modal body -->
<div class="modal-body">
	<%= render partial: "update" %>
</div>

<!-- Modal footer -->
<div class="modal-footer">
	<button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
</div>

app/views/comments/_form.html.erb
<div class="container">
<br>
	<div class="col-md-12">
		<%= form_for [@post , @post.comments.build], remote: true do |f| %>
			<%= f.text_area :content, class: 'form-control', placeholder: 'Add your comment here....!', required: true %><br>
			<%= f.submit 'Comment', class: 'form-control btn btn-primary' %>
		<% end %>
	</div>
</div>

app/views/comments/_index.html.erb
<div class="col-md-12 comments">
  <% @post.comments.each do |comment| %>
   <%= render partial: "comment", locals: {comment: comment} %>   
  <% end %>
</div>
 <%= render partial: "form" %>

<!-- Modal -->
<div class="modal" id="modal-comment">
  <div class="modal-dialog">
    <div class="modal-content">
  </div>
</div>

app/views/comments/_update.html.erb
<div class="col-md-12">
  <%= form_for @comment, remote: true do |f| %>
    <%= f.text_area :content, class: 'form-control' %><br>
    <%= f.submit "update", class: 'form-control btn btn-primary' %>
 <% end %>
</div>

app/views/comments/create.js.erb
$(".comments").append("<%= escape_javascript render(partial: 'comment', locals:{comment: @comment,post: @post}) %>")
$("#post-<%= @post.id %>-comment").html("<%= escape_javascript render(partial: '/posts/post_comment', locals: { post: @post }) %>")

app/views/comments/destroy.js.erb
$("#post-<%= @post.id %>-comment").html("<%= escape_javascript render(template: 'posts/_post_comment', locals: { post: @post }) %>")
$("#comment-<%= @comment.id %>").remove();

app/views/comments/edit.js.erb
$("#modal-comment").find(".modal-content").html("<%= j (render partial: 'edit', locals: { comment: @comment }) %>")
 $("#modal-comment").modal();
 

app/views/comments/index.html.erb
<div class= "clearfix"></div>
  
  <div class="col-md-12">
    <% @post.comments.each do |comment| %>
   <div class="post">
      <%= comment.content %>
  <div class="actions float-right">
  <%= link_to 'Edit', edit_comment_path(comment) %> |
  <%= link_to 'Destroy', comment_path(comment),method: :delete,data: { confirm: 'Are you sure?' } %> |
 
 <% pre_like = comment.likes.find_by_user_id(current_user.id) %>
      <% if pre_like %>
      <%= link_to 'Unlike', like_comment_path(comment) %>
      <% else %>
       <%= link_to 'Like', like_comment_path(comment) %> 
      <% end %> (<%= comment.likes.count %>)
 </div>
</div>
 
<% end %>

<%= render partial: "form" %>

<%= link_to 'back', posts_path %> 
<%#= link_to 'New comment', new_post_comment_path(@post) %>

app/views/comments/index.js.erb
// if (!$("#post-<%= @post.id %>").is(":visible")) {

$("#post-<%= @post.id %>").append("<%= escape_javascript render(partial: 'index', locals: { post: @post, comments: @comments }) %>")

// $("#post-<%= @post.id %>").prepend();
// $("#post-<%= @post.id %>").slideToggle();

app/views/comments/like.js.erb
$("#like-comment-<%= @comment.id %>").html("<%= escape_javascript render(partial: 'comment_like', locals: { comment: @comment }) %>")

app/views/comments/update.js.erb
$("#comment-<%= @comment.id %>").html("<%= escape_javascript render(partial: 'comment_content', locals: { comment: @comment }) %>")
$("#modal-comment").modal('hide');			