config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'
  get 'welcome/home'
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        omniauth_callbacks: 'users/omniauth_callbacks'
        
      }
   resources :profiles
  resources :posts do 
    member do 
      get :like
    end
    collection do
      get :search
    end
    resources :comments, only: [:index, :new, :create]
  end
  #resources :comments, only: [:edit, :show, :update, :destroy]
  resources :comments, except: [:index, :new, :create] do 
    member do 
      get :like
    end
  end
  #root 'posts#index'
  
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :comments , dependent: :destroy
	has_many :likes, :as => :likeable , dependent: :destroy
	belongs_to :user
	validates :title, presence: true, length: { maximum: 100 }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :find_post, only:[:show, :edit,:update, :destroy]
	def index
		@posts = Post.all.order("created_at DESC")
		@post = current_user.posts.new
	end
	
	def new
		@post = current_user.posts.new
	end

	def create
		@post = current_user.posts.new(post_params)
		@post.save
   	end
	
   	
   	def search
   		@posts = Post.where("title LIKE ? ", "%#{params[:query]}%" )
   	end

	def edit	
	end
	
	def like
    	@post = Post.find(params[:id])
    	if @post.likes.find_by_user_id(current_user.id).present?
        	@post.likes.find_by_user_id(current_user.id)&.destroy
    	else
      		@post.likes.create(user_id: current_user.id)
    	end
  	end
	
	def update
		 @post.update(post_params)
	end

	def show
		@comments = Comment.where(post_id: @post)
		@profile = current_user.profile
	end
	
	def destroy
  		 @post.destroy 
	end

	private
	
	def find_post
		@post = Post.find(params[:id])
	end
	
	def post_params
		 params.require(:post).permit(:title, :description)
	end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_edit.html.erb
<!-- Modal Header -->
<div class="modal-header">
  <h4 class="modal-title">Edit Post</h4>
  <button type="button" class="close" data-dismiss="modal">&times;</button>
</div>

<!-- Modal body -->
<div class="modal-body">
  <%= render partial: "form" %>
</div>
<div class="error"></div>
<!-- Modal footer -->
<div class="modal-footer">
  <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
</div>

    

app/views/posts/_form.html.erb
<div class="col-md-12">
	<br>
	<%= form_for @post, remote: true do |f| %>
	  <%= f.text_area :title, class: 'form-control text-content', placeholder: 'Add your post here....!', required: true %>
	  <h6 align="right" class="count_message"></h6><br>
	  <%= f.submit class: 'form-control btn btn-primary' %>
	<% end %>
</div>

app/views/posts/_post.html.erb
<div class="post" id="post-<%= post.id%>">
  <%= render partial: "post_content", locals: { post: post } %>
</div>

app/views/posts/_post_comment.html.erb
  <%= link_to 'comment', post_comments_path(post.id), remote: true %>
  (<%= post.comments.count %>)

app/views/posts/_post_content.html.erb
<%= post.title %>
<div class="actions float-right">
	<span id="post-<%= post.id %>-comment">
      <%= render partial: "post_comment", locals: {post: post} %>
  </span>|
  <% if post.user_id == current_user.id %>
    <%= link_to 'edit', edit_post_path(post), remote: true, 'data-toggle': "modal", 'data-target': "#modal-window" %> | 
    <%= link_to 'delete', post_path(post), method: "DELETE" ,remote: true, data: {confirm: "Are you sure you want to delete?"} %> |
  <% end %>
  <span id="like-post-<%= post.id %>">
      <%= render partial: "post_like", locals: {post: post} %>
  </span>
</div>

app/views/posts/_post_like.html.erb
<% liked = post.likes.find_by_user_id(current_user.id).present? %>
<% if liked %>
  <%= link_to 'unlike', like_post_path(id: post.id), remote: true %>
<% else %>
  <%= link_to 'like', like_post_path(id: post.id), remote: true %>
<% end %>
(<%= post.likes.count %>)

app/views/posts/_posts.html.erb
<% posts.each do |post| %>
  <%= render partial: "post", locals: {post: post} %>
<% end %>

app/views/posts/create.js.erb
if (<%= @post.errors.any? %>) {
  $("#error").html("<%= @post.errors.full_messages.first %>");  
} else {
$(".posts").prepend("<%= escape_javascript render(partial: 'post', locals:{post: @post}) %>");
}
$("#counting").val('');

app/views/posts/destroy.js.erb
$("#post-<%= @post.id %>").remove();

app/views/posts/edit.js.erb
$("#modal-window").find(".modal-content").html("<%= j (render partial: 'edit', locals: { post: @post }) %>")
$("#modal-window").modal();

app/views/posts/index.html.erb
<br>
<input class="form-control" id="myInput" type="text" placeholder="Search..">
<br>
<%= render partial: "form" %>
<hr>
<div class="col-md-12 posts" id="posts">
  <%= render partial: "posts", locals: { posts: @posts } %>
</div>
  


<!-- Modal -->
<div class="modal" id="modal-window">
  <div class="modal-dialog">
    <div class="modal-content">
  </div>
</div>

<!-- <script>
$(document).ready(function(){
  $("#myInput").on("keyup", function()  {
    var input, filter, ul, li, a, i, txtValue;
    input = document.getElementById("myInput");
    filter = input.value.toUpperCase();
    for (i = 0; i < post.length; i++) {
        
        if (li[0].toUpperCase().includes(input)) {
            li[i].style.display = "kkkk";
        } 
        else
         {
            li[i].style.display = "none";
        }
    }
}
)}
</script> -->
<!-- <script>
    var input = $(this).val()
    $.ajax({
      data: { query: input },
      dataType: 'json',
      url: '/posts/search',
      success: function() {
      }
</script> -->
<!-- <script>
  $(document).ready(function(){
    $("#myInput").on("keyup", function() {
      var value = $(this).val().toLowerCase();
      $(".posts").filter(function() {
        $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
      });
    });
  });
</script> -->

<script type="text/javascript">
  var text_max = 10;
  var str = "maximum 10 characters";

  $(document).on('keydown', '.text-content', function() {
    var text_length = $(this).val().length;
    var text_remaining = text_max - text_length;
    var count_div = $(this).parent('form').find('.count_message')
    if (text_remaining <= 0) {
      count_div.html(str.fontcolor('red'));
      if (event.keyCode == "08")
      {
        return true
      }
      else
      {
        return false
      }
    };
    count_div.html(text_remaining + ' characters');
  });
</script>
<script>
  $(document).ready(function(){
    $("#myInput").on("keyup", function(){
      var input = $(this).val()
      $.ajax({
        data: { query: input },
        type: 'GET',
        url: '/posts/search',
        success: function() {

      }
      });
    })
  });
</script>

app/views/posts/like.js.erb
$("#like-post-<%= @post.id %>").html("<%= escape_javascript render(partial: 'post_like', locals: { post: @post }) %>")

app/views/posts/search.js.erb
$(".posts").html("<%= escape_javascript render(partial: 'posts', locals: { posts: @posts }) %>")

app/views/posts/update.js.erb
$("#post-<%= @post.id %>").html("<%= escape_javascript render(partial: 'post_content', locals: { post: @post }) %>")
$("#modal-window").modal('hide');