config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'
  get 'welcome/home'
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        omniauth_callbacks: 'users/omniauth_callbacks'
        
      }
   resources :profiles
  resources :posts do 
    member do 
      get :like
    end
    collection do
      get :search
    end
    resources :comments, only: [:index, :new, :create]
  end
  #resources :comments, only: [:edit, :show, :update, :destroy]
  resources :comments, except: [:index, :new, :create] do 
    member do 
      get :like
    end
  end
  #root 'posts#index'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post 
  belongs_to :user
  has_many :likes, :as => :likeable , dependent: :destroy
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post, optional: true
  belongs_to :user, optional:true
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :comments , dependent: :destroy
	has_many :likes, :as => :likeable , dependent: :destroy
	belongs_to :user
	validates :title, presence: true, length: { maximum: 100 }
end

app/models/profile.rb
class Profile < ApplicationRecord
	belongs_to :user
  mount_uploader :image, ImageUploader

  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :posts , dependent: :destroy
  has_one :profile , dependent: :destroy
  has_many :comments , dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :user_provider, :dependent => :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook,:google_oauth2]

 # def self.create_from_provider_data(provider_data)
 #    where(provider: provider_data.provider, uid: provider_data.uid).first_or_create do | user |
 #      user.email = provider_data.info.email
 #      user.password = Devise.friendly_token[0, 20]
 #    end
 #  end
 #  def self.create_from_google_data(provider_data)
 #    where(provider: provider_data.provider, uid: provider_data.uid).first_or_create do | user |
 #      user.email = provider_data.info.email
 #      user.password = Devise.friendly_token[0, 20]
      
 #      user.save
 #    end
 #  end
end

app/models/user_provider.rb
class UserProvider < ApplicationRecord
  belongs_to :user
  def self.find_for_provider_data(auth)
    user_provider = UserProvider.where(:provider => auth.provider, :uid => auth.uid).first
    if user_provider.nil?
      registered_user = User.where(:email => auth.info.email).first
      if registered_user.nil?
        user = User.create!(name: auth.info.name,email: auth.info.email,password: Devise.friendly_token[0,20])
        user_provider = UserProvider.create!(provider:auth.provider,uid:auth.uid,user_id: user.id)
        user 
      else
        UserProvider.create!(provider: auth.provider,uid: auth.uid,user_id: registered_user.id)
          registered_user
      end
    else
      user_provider.user    
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	layout :set_layout

	def set_layout
		if devise_controller?
			"devise"
		else
			"application"
		end
	end

	def after_sign_in_path_for(resource)		
		if resource.profile.present?
 			posts_path
		else
 			new_profile_path 
		end
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	
  def index
    @post = Post.find(params[:post_id])
    @comments = @post.comments
  end
  
  def new
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new
  end
  
  def create
    @post = Post.find(params[:post_id])
    if @post.present?
      @comment = @post.comments.create(comment_params)
      @comment.user_id = current_user.id
      @comment.save
    end
  end

  def edit
   @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    @comment.update(comment_params)
  end

  def destroy
    @comment = Comment.find(params[:id])
    @post = @comment.post
    #@post = Post.find_by(id: @comment.post_id)
    @comment.destroy
  end 

  def like
    @comment = Comment.find(params[:id])
    if @comment.likes.find_by_user_id(current_user.id).present?
      @comment.likes.find_by_user_id(current_user.id)&.destroy
    else
       @comment.likes.create(user_id: current_user.id)
    end
     # redirect_to post_comments_path(id: @comment.id,post_id: @comment.post_id)
  end

  private

  def comment_params
    params.require(:comment).permit(:post_id, :content)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :find_post, only:[:show, :edit,:update, :destroy]
	def index
		@posts = Post.all.order("created_at DESC")
		@post = current_user.posts.new
	end
	
	def new
		@post = current_user.posts.new
	end

	def create
		@post = current_user.posts.new(post_params)
		@post.save
   	end
	
   	
   	def search
   		@posts = Post.where("title LIKE ? ", "%#{params[:query]}%" )
   	end

	def edit	
	end
	
	def like
    	@post = Post.find(params[:id])
    	if @post.likes.find_by_user_id(current_user.id).present?
        	@post.likes.find_by_user_id(current_user.id)&.destroy
    	else
      		@post.likes.create(user_id: current_user.id)
    	end
  	end
	
	def update
		 @post.update(post_params)
	end

	def show
		@comments = Comment.where(post_id: @post)
		@profile = current_user.profile
	end
	
	def destroy
  		 @post.destroy 
	end

	private
	
	def find_post
		@post = Post.find(params[:id])
	end
	
	def post_params
		 params.require(:post).permit(:title, :description)
	end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	before_action :set_profile, only: [:edit, :update]
	def new
		@profile = Profile.new
	end
	
	def create
		@profile = current_user.build_profile(profile_params)
		if @profile.save
			
    		redirect_to posts_path
  		else
    		render 'new'
  		end
	end
	
	def edit
		@profile = Profile.find(params[:id])
	end
	
	def update
		
		@profile.update(profile_params)    	
		render json: { success: true, message: "Profile updated successfully!" }
	end
	
	def show
		@profile = Profile.find(params[:id])
	end

	private
	def set_profile
  		@profile = current_user.profile
	end
	def profile_params
		params.require(:profile).permit(:fname, :lname, :address, :image)
	end
end

app/controllers/transaction_controller.rb
class TransactionController < ApplicationController
require "rubygems"
require "braintree"

gateway = Braintree::Gateway.new(
  :environment => :sandbox,
  :merchant_id => "rr5znhwwvd7nh3xs",
  :public_key => "hdbf8fngdm47xv6f",
  :private_key => "6fbad75695c175a835de33bf8ab98a5a",
)

result = gateway.transaction.sale(
  :amount => "1000.00",
  :payment_method_nonce => nonce_from_the_client,
  :options => {
    :submit_for_settlement => true
  }
)

if result.success?
  puts "success!: #{result.transaction.id}"
elsif result.transaction
  puts "Error processing transaction:"
  puts "  code: #{result.transaction.processor_response_code}"
  puts "  text: #{result.transaction.processor_response_text}"
else
  p result.errors
end
def customer
	result = gateway.customer.create(:first_name => "Josh")
	if result.success?
  		puts "Created customer #{result.customer.id}"
	else
  		puts "Validations failed"
  		result.errors.for(:customer).each do |error|
    	puts error.message
  	end
end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def home
  	redirect_to new_user_session_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def flash_class(level)
    case level.to_sym
      when :notice then "alert alert-info"
      when :success then "alert alert-success"
      when :error then "alert alert-danger"
      when :alert then "alert alert-primary"
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/transaction_helper.rb
module TransactionHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/common/_flash_message.html.erb
<% flash.each do |key, value| %>
  <div class="<%= flash_class(key) %>">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= value %>
  </div>
<% end %>

app/views/common/_header.html.erb
<% if user_signed_in? %>
  <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <a class="navbar-brand" href="/">LOGO</a>
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <% if current_user.profile.present? %>
        <%= link_to 'Profile', profile_path(current_user.profile), class: "nav-link" %>
        <% end %>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <%= link_to 'log out', destroy_user_session_path, method: "DELETE", class: "nav-link" %>
      </li>
    </ul>
  </nav>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--Fontawesome CDN-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    
  </head>

  <body>

    <%= render partial: 'common/header' %>
    <%= render partial: 'common/flash_message' %>
   <!--  <div class="container">
      <div class="d-flex justify-content-center h-100"> -->
        <%= yield %>
     <!--  </div>
    </div> -->
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
  <head>
    <title>Blog</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->
    <%= stylesheet_link_tag    'devise', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--Fontawesome CDN-->
    
  </head>

  <body>
    <%= render partial: 'common/header' %>
    <%= render partial: 'common/flash_message' %>
   
        <%= yield %>
    
  </body>
</html>